package com.global.shop.model.notification;

public enum NotificationType {

    PERMISSION_TO_ADMIN,
    PERMISSION_TO_MODERATOR,
    APPROVE_PERMISSION_INFO_TO_USER,
    APPROVE_PERMISSION_INFO_TO_ADMIN,
    DECLINE_PERMISSION_INFO_TO_USER,
    DECLINE_PERMISSION_INFO_TO_ADMIN,
    INFO_TO_USER,
    INFO_TO_ADMIN

}
