version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.0
    container_name: zookeeper
    ports:
      - 54132:54132
    command: /etc/confluent/docker/run
    environment:
      - ZOOKEEPER_CLIENT_PORT=54132
  kafka:
    image: confluentinc/cp-kafka:5.3.0
    container_name: kafka
    ports:
      - 54133:54133
    command: /etc/confluent/docker/run
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_LISTENERS=LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://localhost:54133
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=LISTENER_DOCKER_INTERNAL
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:54132
      - KAFKA_BROKER_ID=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - TOPIC_AUTO_CREATE=TRUE
    depends_on:
      - zookeeper

  auth-postgres-db:
    image: mdillon/postgis:10
    container_name: auth-postgres-db
    ports:
      - 5434:5432
    environment:
      - POSTGRES_DB=education_auth
      - POSTGRES_USER=education-auth
      - POSTGRES_PASSWORD=education-auth
    # Default script execution when container is run
    #volumes:
    #  - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  auth-education:
    image: education_auth:latest.20.8-SNAPSHOT
    container_name: auth-education
    ports:
      - 8081:8081
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-postgres-db:5432/education_auth?autoReconnect=true&useSSL=false
    depends_on:
      - auth-postgres-db

  app-postgres-db:
    image: mdillon/postgis:10
    container_name: app-postgres-db
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=education_app
      - POSTGRES_USER=education-app
      - POSTGRES_PASSWORD=education-app
  app-education:
    image: education_app:latest.20.8-SNAPSHOT
    container_name: app-education
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://app-postgres-db:5432/education_app?autoReconnect=true&useSSL=false
      - SECURITY_OAUTH2_CLIENT_ACCESSTOKENURI=http://auth-education:8081/auth/oauth/token
      - SECURITY_OAUTH2_CLIENT_USERAUTHORIZATIONURI=http://auth-education:8081/auth/oauth/authorize
      - SECURITY_OAUTH2_RESOURCE_USER_INFO_URI=http://auth-education:8081/auth/user/me
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:19092
    depends_on:
      - app-postgres-db
      - auth-education
      - zookeeper
      - kafka