---
- name: Update all packages
  apt:
    update_cache: yes

- name: Upgrade all packages
  apt:
    upgrade: dist

- name: Install required packages
  apt:
    name: [ 'apt-transport-https',
            'ca-certificates',
            'curl',
            'gnupg-agent',
            'software-properties-common',
            'python-pip' ]
    state: latest
    update_cache: yes
  become: true

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Save the current Ubuntu release version into a variable
  shell: lsb_release -cs
  register: ubuntu_version

- name: Add Docker Repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_version.stdout }} stable"
    state: present

- name: Install Docker
  apt:
    name: "docker-ce"
    state: present
