---
- name: Upgrade all packages
  yum:
    name: '*'
    state: latest

- name: Install Docker
  yum:
    name: [ 'docker', 'python-pip', 'python-devel', 'gcc' ]
    state: latest
  become: yes

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: yes
