spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shop?autoReconnect=true&useSSL=false
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
      temp.use_jdbc_metadata_defaults: false
      #show_sql: true
      #use_sql_comments: true
      #format_sql: true
      #type: trace
  flyway:
    enabled: true
    baseline-on-migrate: true
    out-of-order: true
    url: ${spring.datasource.url}
    user: flyway
    password: flyway