package com.global.education.model.notification;

public enum NotificationType {

    PERMISSION_TO_ADMIN,
    APPROVE_PERMISSION_INFO_TO_USER,
    APPROVE_PERMISSION_INFO_TO_ADMIN,
    DECLINE_PERMISSION_INFO_TO_USER,
    DECLINE_PERMISSION_INFO_TO_ADMIN,
    INFO_TO_USER

}
