spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/education_app?autoReconnect=true&useSSL=false
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
      temp.use_jdbc_metadata_defaults: false
      #show_sql: true
      #use_sql_comments: true
      #format_sql: true
      #type: trace
  flyway:
    enabled: true
    baseline-on-migrate: true
    out-of-order: true
    url: ${spring.datasource.url}
    user: postgres
    password: postgres

kafka-topics:
  bootstrap-server: localhost:9092
  user-finish-lesson-event:
    enabled: true
    topic: education-finish-lesson-event
    producer-properties:
      "[bootstrap.servers]": ${kafka-topics.bootstrap-server}
      "[key.serializer]": org.apache.kafka.common.serialization.StringSerializer
      "[value.serializer]": org.apache.kafka.common.serialization.StringSerializer
  user-start-course-event:
    enabled: true
    topic: education-start-course-event
    producer-properties:
      "[bootstrap.servers]": ${kafka-topics.bootstrap-server}
      "[key.serializer]": org.apache.kafka.common.serialization.StringSerializer
      "[value.serializer]": org.apache.kafka.common.serialization.StringSerializer

server:
  servlet:
    context-path: /app

# Can working without the next block
security:
  oauth2:
    client:
      clientId: my-client
      clientSecret: secret
      accessTokenUri: http://localhost:8081/auth/oauth/token
      userAuthorizationUri: http://localhost:8081/auth/oauth/authorize
    resource:
      id: ${spring.application.name}
      jwt:
        keyValue:
          d2ViLWNsaWVudDp3ZWItY2xpZW50LXNlY3JldA==