version: '3'
services:
  postgres-db:
    image: mdillon/postgis:10
    container_name: postgres-db
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=education_app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    # Default script execution when container is run
    #volumes:
    #  - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  education-app:
    build: ..
    container_name: education-app
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/education_app?autoReconnect=true&useSSL=false
    depends_on:
      - postgres-db