spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/education_auth?autoReconnect=true&useSSL=false
    username: education-auth
    password: education-auth
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
      temp.use_jdbc_metadata_defaults: false
      #show_sql: true
      #use_sql_comments: true
      #format_sql: true
      #type: trace
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: ${spring.datasource.url}
    user: flyway
    password: flyway

server:
  port: 8081
  servlet:
    context-path: /auth

#logging.level:
#  org.springframework:
#    security: DEBUG