spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/education_auth?autoReconnect=true&useSSL=false
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
      temp.use_jdbc_metadata_defaults: false
      #show_sql: true
      #use_sql_comments: true
      #format_sql: true
      #type: trace
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: ${spring.datasource.url}
    user: postgres
    password: postgres

kafka-topics:
  bootstrap-server: localhost:9092
  user-finish-lesson-event:
    enabled: true
    topic: education-finish-lesson-event
    consumer-properties:
      "[bootstrap.servers]": ${kafka-topics.bootstrap-server}
      "[key.deserializer]": org.apache.kafka.common.serialization.StringDeserializer
      "[value.deserializer]": org.apache.kafka.common.serialization.StringDeserializer
      "[group.id]": "user-finish-lesson-event-group"
  user-start-course-event:
    enabled: true
    topic: education-start-course-event
    consumer-properties:
      "[bootstrap.servers]": ${kafka-topics.bootstrap-server}
      "[key.deserializer]": org.apache.kafka.common.serialization.StringDeserializer
      "[value.deserializer]": org.apache.kafka.common.serialization.StringDeserializer
      "[group.id]": "user-start-course-event-group"

server:
  port: 8081
  servlet:
    context-path: /auth

#logging.level:
#  org.springframework:
#    security: DEBUG