version: '3'
services:
  jenkins:
    container_name: jenkins
    build: .
    user: root 
    ports:
      - "8090:8080"
    volumes:
      - "/home/aleksandr/jenkins_mount:/var/jenkins_home"
      - //var/run/docker.sock:/var/run/docker.sock
    networks:
      - net

networks:
  net:
 
