version: '3.8'
services:
  jenkins:
    # Use the following line to correct docker works
    network_mode: host
    container_name: jenkins
    build: .
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/aleksandr/jenkins_mount:/var/jenkins_home
